---

- name: Invent all
  hosts: medsi-all:13-DC-all:dc-asr
  gather_facts: false
  connection: local
  serial: 30

  tasks:

    - name: Facts
      ios_facts:
        gather_subset:
          - hardware
        provider: "{{ cli }}"
      register: ios_facts_result

#    - name: Create all_facts dir
#      file:
#        path: ./all_facts/
#        state: directory
#        mode: 0755

#    - name: Copy facts to files
#      copy:
#        content: "{{ ios_facts_result | to_nice_json }}"
#        dest: "all_facts/{{inventory_hostname}}_facts.json"

    - name: set all serials if exists
      set_fact:
        serial: "{{ ansible_net_stacked_serialnums | join(',') }}"
      when: ansible_net_stacked_serialnums is defined
    - name: set one serial
      set_fact:
        serial: "{{ ansible_net_serialnum }}"
      when: ansible_net_stacked_serialnums is not defined

    - name: get location
      ios_command:
        commands:
          - show snmp location
        provider: "{{ cli }}"
      register: location

    - name: file write
      lineinfile:
        create: yes
        path: ./invent.csv
        # fisrt 5 column for https://cway.cisco.com/mydevices:
        # Serial Number;Device Name / Hostname;Tags;Notes;Software Version
        line: "{{ serial }};\
               {{ ansible_net_hostname }};\
               ;\
               {{ location.stdout[0] }};\
               {{ ansible_net_version }};\
               {{ inventory_hostname }};\
               {{ ansible_net_model }}"

- name: expand serials and remove last two column
  connection: local
  hosts: localhost

  tasks:

    - name: convert csv
      shell: |
        python3 convert.py > for_upload.csv
      delegate_to: localhost

